
# title: Design
include: [article, table, form]

# design:
hero: /img/og.png
heading: Big heading
subtitle: With optional description
dark: true


# TODO: Gabarito: [600, 500, 400]
font:
  family: Gabarito
  weights: [600, 500, 400]

colors:
  main: ALL
  grays: ALL
  accents: ALL



